config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
require 'cpf_cnpj'

class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, 'valid_email_2/email': true
  validates :cpf, presence: true, uniqueness: true
  validate :valid_cpf
  validates :phone, format: { with: /\A\d+\z/ }

  scope :search_by_substring, ->(query) {
    where('name ILIKE :query OR email ILIKE :query OR phone ILIKE :query OR cpf ILIKE :query', query: "%#{query}%")
  }

  def valid_cpf
    errors.add(:cpf, 'inválido ') unless CPF.valid?(cpf)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    if params[:query] && !params[:query].empty?
      @users = User.search_by_substring(params[:query])
    else
      @users = User.all
    end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)


    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), t('users.create.success') }
        format.json { render :show, status: :created, location: @user }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if @user.update(user_params)
      redirect_to users_path(@user), notice: t('users.destroy.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    redirect_to users_path, notice: t('users.destroy.success')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :phone, :cpf)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def format_phone(number)
    "(#{number[0..1]}) #{number[2..6]}-#{number[7..11]}"
  end

  def format_cpf(cpf)
    "#{cpf[0..2]}.#{cpf[3..5]}.#{cpf[6..8]}-#{cpf[9..10]}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoFestalab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application.sass", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for user, html: { class: "form container user" },
                          data: { controller: "input-mask" } do |f| %>

  <% if @user.errors.any? %>
    <div class="error-message">
      <%= @user.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <div class="inputs">
     <%= f.input :name, input_html: { autofocus: true }%>
    <%= f.input :email%>
    <%= f.input :phone, input_html: { data: { "input-mask-target": "phone" } } %>
    <%= f.input :cpf, input_html: { data: { "input-mask-target": "cpf" } } %>
  </div>

  <div class="buttons">
    <%= link_to t('general.cancel'), users_path, class: "btn btn--light" %>
    <%= f.submit class: "btn btn--secondary"  %>
  </div>

<% end %>

app/views/users/_user.html.erb
<%= turbo_frame_tag user do %>
  <div class="user">
    <%= link_to user.name, user_path(user), data: { turbo_frame: "_top" } %>

    <div class="user__actions">
      <%= button_to t('actions.simple_destroy'),
                    user_path(user),
                    method: :delete,
                    form: { data: { turbo_frame: "_top" }},
                    data: { turbo_confirm: t('general.confirmations.delete_user') },
                    class: 'btn btn--light' %>
      <%= link_to t('actions.simple_edit'),
                  edit_user_path(user),
                  class: 'btn btn--light' %>
    </div>
  </div>
<% end %>

app/views/users/create.turbo_stream.erb
<%= turbo_stream.prepend "users", partial: "users/user", locals: { user: @user } %>
<%= turbo_stream.update User.new, "" %>

app/views/users/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Voltar"), user_path(@user) %>

  <div class="header">
    <h1>Editar</h1>
  </div>

  <%= turbo_frame_tag @user do %>
    <%= render "form", user: @user %>
  <% end %>
</main>

app/views/users/index.html.erb
<main class="container">
  <div class="header">
    <h1><%= t('general.title') %></h1>

     <%= link_to t('actions.new', model: t('activerecord.models.user')), new_user_path,
                class: "btn btn--primary",
                data: { turbo_frame: dom_id(User.new)} %>

    <%= simple_form_for users_path, method: :get,
                                  html: { class: "search form" } do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: t('general.search_placeholder'),
            data: { search_target: "input", action: "input->search#search" }
        %>
      <%= submit_tag t('general.search'), name: "", class: "btn btn-primary" %>
    <% end %>

  </div>

  <%= turbo_frame_tag User.new %>

  <%= turbo_frame_tag "users" do %>
    <% @users.each do |user| %>
      <%= render user %>
    <% end %>
  <% end %>
</main>

app/views/users/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Voltar"), users_path %>

  <div class="header">
    <h1>Novo usuário</h1>
  </div>
  <%= turbo_frame_tag @user do %>
    <%= render "form", user: @user %>
  <% end %>
</main>

app/views/users/show.html.erb
<main class="container">
  <%= link_to t('actions.back').html_safe , users_path %>
  <div class="header user show">
    <h1>
      <%= @user.name %>
    </h1>
    <p> <%= format_phone(@user.phone) %> </p>
    <p> <%= @user.email %> </p>
    <p> <%= format_cpf(@user.cpf) %> </p>
  </div>

  <div class="user__actions">
    <%= link_to t('actions.edit', model: t('activerecord.models.user')), edit_user_path(@user),
                class: 'btn btn--secondary' %>
    <%= button_to t('actions.destroy', model: t('activerecord.models.user')), @user,
                  method: :delete, class: 'btn btn--light' %>
  </div>
</main>